language: node_js
node_js:
  - "6.9"
  - "7.1"
sudo: false
env:
  - NODE_ENV='test'
script:
  - cp env.example.js env.js
  - npm run lint
  - npm test
  - npm run bundle:ios
matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      sudo: required
      node_js: false
      before_install:
        - nvm install 7
        - node --version
        - travis_retry curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - travis_retry sudo apt-get update -qq
        - travis_retry sudo apt-get install -y -qq yarn
      install:
        - yarn
      android:
        components:
          - tools
          - platform-tools
          - build-tools-23.0.1
          - android-23
          - build-tools-26.0.1
          - android-26
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
      script:
        - cd android && ./gradlew assembleDebug && ./gradlew assembleRelease
    - language: objective-c
      os: osx
      osx_image: xcode8.2
      node_js: false
      before_install:
        - nvm install 7
        - node --version
        - travis_retry npm install -g yarn
        - yarn -version
      install:
        - travis_retry gem install xcpretty
        - travis_retry yarn
      xcode_project: ios/DulceAppTemplate.xcodeproj
      xcode_scheme: ios/DulceAppTemplateTests
      script:
        - cd ios
        - xcodebuild -scheme DulceAppTemplate -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
        - travis_retry xctool run-tests -scheme DulceAppTemplate -sdk iphonesimulator -launch-timeout 90  ONLY_ACTIVE_ARCH=NO